# Generated by Django 4.1.6 on 2023-02-05 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('naves', '0002_tipo_alter_naves_tipo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Naves',
            new_name='Nave',
        ),
    ]
