# Generated by Django 4.1.6 on 2023-02-06 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naves', '0004_nave_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nave',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
